### ISSUE TITLE
Make it work with FraBegynnelsen

### ISSUE THREAD

**Issue by karsten-kuepper** [bcc-code/bcc-identity-server-dummy#1]
We created a copy of Production and called it staging10 and configured it to use the dummy.login.bcc.no.
However it gives us an error:
```
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

We see three differences from what's in gitbook:

1. we have church as an additional scope. Unfortunately it's hardcoded an not easy to remove in php. But removing it manually in the url does not seem to change anything
2. our response_type is `code` vs `token code` in gitbook. Is that important?
3. We only have a state but not a nonce. Is that a problem?

You can also try it yourself on the staging environment.
(it does not have a valid ssl certificate so you need to add an exception for this url)

**Comment by philipdalen** [comment]
@karsten-kuepper thanks for reporting the issue. I have now released an update which now excepts the "church" scope and also the `code` flow. I also confirmed that nonce is not required. I tested this and the IDP now provides a code, I was also able to use the code to get some tokens from the IDP. However when I tested this on the frabegynnelsen website says that the token is invalid. Could you provide me with some logs on how it tries to verify the token, so that I can have a look if there is still something wrong with the IDP.

Thanks

**Comment by rvanoord** [comment]
Essentially got this working on the staging environment. The main issue is that the endpoint configuration needs to be changed for the token endpoint and the userinfo endpoint (don't follow the same convention as Auth0).

See: https://dummy.login.bcc.no/.well-known/openid-configuration

@karsten-kuepper @philipdalen
